export const SERVER_STATUSES = {
  PENDING: 'PENDING',
  ONLINE: 'ONLINE',
  DEGRADED: 'DEGRADED',
  OFFLINE: 'OFFLINE',
  REVOKED: 'REVOKED',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export type ServerStatus = (typeof SERVER_STATUSES)[keyof typeof SERVER_STATUSES];

export const AGENT_STATUSES = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  NOT_INSTALLED: 'NOT_INSTALLED',
  REVOKED: 'REVOKED',
  OUTDATED: 'OUTDATED',
} as const;

export type AgentStatus = (typeof AGENT_STATUSES)[keyof typeof AGENT_STATUSES];

export const CREDENTIAL_STATUSES = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  ROTATED: 'ROTATED',
} as const;

export type CredentialStatus = (typeof CREDENTIAL_STATUSES)[keyof typeof CREDENTIAL_STATUSES];

export const ENROLLMENT_PURPOSES = {
  ENROLL: 'ENROLL',
  ROTATE: 'ROTATE',
} as const;

export type EnrollmentPurpose = (typeof ENROLLMENT_PURPOSES)[keyof typeof ENROLLMENT_PURPOSES];

export const OPERATION_TYPES = {
  REBOOT: 'REBOOT',
  SHUTDOWN: 'SHUTDOWN',
  REFRESH_INVENTORY: 'REFRESH_INVENTORY',
  REFRESH_METRICS: 'REFRESH_METRICS',
  CHECK_UPDATES: 'CHECK_UPDATES',
  UPDATE_AGENT: 'UPDATE_AGENT',
} as const;

export type OperationType = (typeof OPERATION_TYPES)[keyof typeof OPERATION_TYPES];

export const OPERATION_STATUSES = {
  PENDING: 'PENDING',
  DELIVERED: 'DELIVERED',
  RUNNING: 'RUNNING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export type OperationStatus = (typeof OPERATION_STATUSES)[keyof typeof OPERATION_STATUSES];

export const EVENT_TYPES = {
  SERVER_CREATED: 'SERVER_CREATED',
  SERVER_UPDATED: 'SERVER_UPDATED',
  SERVER_DELETED: 'SERVER_DELETED',
  AGENT_ENROLLED: 'AGENT_ENROLLED',
  AGENT_CONNECTED: 'AGENT_CONNECTED',
  AGENT_DISCONNECTED: 'AGENT_DISCONNECTED',
  AGENT_REVOKED: 'AGENT_REVOKED',
  AGENT_ROTATED: 'AGENT_ROTATED',
  AGENT_OUTDATED: 'AGENT_OUTDATED',
  SERVER_ONLINE: 'SERVER_ONLINE',
  SERVER_OFFLINE: 'SERVER_OFFLINE',
  HEALTH_WARNING_STARTED: 'HEALTH_WARNING_STARTED',
  HEALTH_WARNING_RESOLVED: 'HEALTH_WARNING_RESOLVED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_ENDED: 'MAINTENANCE_ENDED',
  OPERATION_REQUESTED: 'OPERATION_REQUESTED',
  OPERATION_SUCCEEDED: 'OPERATION_SUCCEEDED',
  OPERATION_FAILED: 'OPERATION_FAILED',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export const EVENT_SEVERITIES = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
} as const;

export type EventSeverity = (typeof EVENT_SEVERITIES)[keyof typeof EVENT_SEVERITIES];

export const HEALTH_STATUSES = {
  OK: 'OK',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
} as const;

export type HealthStatus = (typeof HEALTH_STATUSES)[keyof typeof HEALTH_STATUSES];

export const HEALTH_REASON_CODES = {
  AGENT_DISCONNECTED: 'AGENT_DISCONNECTED',
  AGENT_NOT_INSTALLED: 'AGENT_NOT_INSTALLED',
  AGENT_OUTDATED: 'AGENT_OUTDATED',
  CPU_HIGH: 'CPU_HIGH',
  MEMORY_HIGH: 'MEMORY_HIGH',
  DISK_HIGH: 'DISK_HIGH',
  METRICS_STALE: 'METRICS_STALE',
  SERVER_OFFLINE: 'SERVER_OFFLINE',
} as const;

export type HealthReasonCode = (typeof HEALTH_REASON_CODES)[keyof typeof HEALTH_REASON_CODES];
